//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDBSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TblMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMusteri()
        {
            this.TblSatislar = new HashSet<TblSatislar>();
        }
    
        public int MusteriId { get; set; }

        [Required(ErrorMessage = "Bu Alani Bos Birakamazsiniz...!")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Ýsim Giriniz...!")]
        public string MusteriAd { get; set; }
        //[Required(ErrorMessage = "Bu Alani Bos Birakamazsiniz...!")]
        //[StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Ýsim Giriniz...!")]
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatislar> TblSatislar { get; set; }
    }
}
